blank_issues_enabled: false
contact_links:
  - name: Brieflow Issues
    url: https://github.com/cheeseman-lab/brieflow/issues
    about: Nearly all issues (env issues, library bugs, etc) should be reported in the brieflow repository.