
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
aggregate:
  cat_columns:
  - gene_symbol_0
  - sgRNA_0
  control_prefix: nontargeting
  feature_start: nucleus_DAPI_mean
  filter_single_gene: false
  group_columns:
  - plate
  - well
  index_columns:
  - tile
  - cell_0
  population_feature: gene_symbol_0
  threshold_conditions:
    nucleus_DAPI_median:
    - 7
    - greater
  transformations_fp: config/transformations.tsv
all:
  root_fp: analysis_root/
cluster:
  channel_combos:
  - - DAPI
    - COXIV
    - CENPA
    - WGA
  - - DAPI
    - CENPA
  correlation_threshold: 0.99
  corum_data_fp: config/corum_data.tsv
  cum_var_threshold: 0.99
  dataset_types:
  - mitotic
  - interphase
  - all
  leiden_resolution: 15
  min_cell_cutoffs:
    all: 3
    interphase: 3
    mitotic: 0
  min_unique_values: 5
  string_data_fp: config/string_data.tsv
  uniprot_data_fp: config/uniprot_data.tsv
  variance_threshold: 0.001
merge:
  det_range:
  - 0.06
  - 0.065
  initial_sites:
  - - 5
    - 0
  - - 141
    - 32
  - - 370
    - 86
  - - 896
    - 212
  - - 1163
    - 270
  - - 1599
    - 376
  ph_metadata_channel: null
  sbs_metadata_channel: null
  sbs_metadata_cycle: 1
  score: 0.1
  threshold: 2
phenotype:
  align: false
  cell_diameter: 53.05782348918437
  cellprob_threshold: 0
  channel_names:
  - DAPI
  - COXIV
  - CENPA
  - WGA
  cyto_index: 1
  cyto_model: cyto3
  dapi_index: 0
  flow_threshold: 0.4
  foci_channel: 2
  gpu: false
  mode: null
  nuclei_diameter: 41.97813156768016
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: true
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_samples_fp: config/sbs_samples.tsv
sbs:
  alignment_method: DAPI
  bases:
  - G
  - T
  - A
  - C
  cell_diameter: 19.835095646937663
  cellprob_threshold: 0
  cyto_index: 4
  cyto_model: cyto3
  dapi_index: 0
  df_design_path: config/pool10_design.tsv
  flow_threshold: 0.4
  gpu: false
  keep_extras: false
  mode: null
  nuclei_diameter: 9.166995688475083
  q_min: 0
  segmentation_cycle_index: 10
  threshold_peaks: 400
